#
# For documentation: https://docs.codecov.io/docs/codecovyml-reference
# Incremental settings: https://codecov.io/gh/twisted/incremental/settings/yaml
#
# We want 100% coverage for new patches to make sure we are always increasing
# the coverage.
#
codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  status:
    patch:
      default:
        # New code should have 100% CI coverage as the minimum
        # quality assurance measurement.
        # If there is a good reason for new code not to have coverage,
        # add inline pragma comments.
        target: 100%
    project:
      default:
        # Temporary allow for a bit of slack in overall code coverage due to
        # swinging coverage that is not triggered by changes in a PR.
        # See: https://twistedmatrix.com/trac/ticket/10170
        threshold: 0.02%
      tests:
        # Make sure we run each test at least once.
        # If we don't have 100% coverage for tests, it meant that some
        # tests are always skipped.
        target: 100%
        paths:
          - "src/incremental/tests/*"


# See https://docs.codecov.io/docs/pull-request-comments
comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: true  # if true: only post the comment if coverage changes


# See https://docs.codecov.io/docs/github-checks
github_checks:
  # We want codecov to send inline PR comments for missing coverage.
  annotations: true
